[package]
name = "ssh_bc_server"
version = "0.1.0"
edition = "2021"

[dependencies]
rand_core = "0.9.3"
reqwest = { version = "0.12.15", features = ["json"] }
russh = "0.52.1"
serde_json = "1.0.140"
tokio = "1.45.0"
unicode-width = "0.2.0"
